[package]
name = "ragal-linker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dlopen2 = "0.7.0"
once_cell = "1.19.0"
# tauri = {version = "1.5", features = ["dialog-all"]}